### ISSUE TITLE
License of AC Power flow code?

### ISSUE THREAD

**Issue by pierre-haessig** [fBaz92/Electrical-engineering#1]
Dear Francesco Bazzani,

I came across your AC Power flow code while searching for a pure Python implementation (thanks to the good referencing of your [blog post](https://medium.com/@frabazzani/powerflow-analysis-using-python-f8c9af89cd89)). I was wondering if you would accept reuse of your code (I'm thinking of the [ElectricalObjects.py](https://github.com/fBaz92/Electrical-engineering/blob/main/Loadflow/Utilities/ElectricalObjects.py) module), and if yes if you could specify a license for that code.

For a bit of background: I'll soon teach a short introduction to power grids, and I was considering having an interactive experiment of AC power flow. Something in the spirit of https://matpower.app/, but with much simpler inputs and a customized graphical output which highlights better the power flow results. With the purpose of having students running the code with zero installation, I need the code to run on [JupyterLite](https://jupyterlite.readthedocs.io/en/latest/), which excludes non-pure Python packages like Pandapower.

Thanks for your feedback

Best regards,
Pierre

**Comment by fBaz92** [comment]
Hi Pierre,You can reuse it for your classes and I’m really happy you find it interesting.In this period I’m overwhelmed with work, so I’ll try to spend some time selecting the licence of the project.But I have 2 asks for you:1) could you share the code that you will develop in your class? 2) could you please cite me in the resources of your class? Also would be great to see the resources (only because I’m kind of a nerd).Best regards and many thanks for your appreciation Francesco Il giorno 16 mag 2023, alle ore 16:49, Pierre Haessig ***@***.***> ha scritto:﻿
Dear Francesco Bazzani,
I came across your AC Power flow code while searching for a pure Python implementation (thanks to the good referencing of your blog post). I was wondering if you would accept reuse of your code (I'm thinking of the ElectricalObjects.py module), and if yes if you could specify a license for that code.
For a bit of background: I'll soon teach a short introduction to power grids, and I was considering having an interactive experiment of AC power flow. Something in the spirit of https://matpower.app/, but with much simpler inputs and a customized graphical output which highlights better the power flow results. With the purpose of having students running the code with zero installation, I need the code to run on JupyterLite, which excludes non-pure Python packages like Pandapower.
Thanks for your feedback
Best regards,
Pierre

**Comment by fBaz92** [comment]
Added licence
